# Generated by Django 4.2.7 on 2023-11-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
