# Generated by Django 4.2.7 on 2023-11-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_image', '0002_alter_picture_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='question',
        ),
    ]
